### ISSUE TITLE
[Init] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#1]
## Todo
- [x] .gitignore 파일 추가
- [x] 폴더링
- [x] 색상/폰트/컬러 에셋 추가
- [x] SPM 파일 추가 (SnapKit, Then)
- [x] 화면 연결 
- [x] 세로모드/라이트모드 고정
- [x] DisplayName 변경

**Comment by shb03323** [comment]
안녕하세요.
