### ISSUE TITLE
[Feat] 메인 Bottom Sheet UI 구현

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#11]
## Todo
- [x] 메인 상단 네비게이션 레이아웃 수정 
- [x] Bottom Sheet UI 구현
- [x] 서버 통신 후 Response Data로 업데이트
- [x] 선택 시 상세 화면으로 이동
- [x] 상세 화면 데이터 전달
