### ISSUE TITLE
[Feat] NiCarNaeCar 프레임워크 구현

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#2]
## Todo
- [x] Util 프레임워크 생성 및 프로젝트에 적용
- [x] 리소스 프레임워크 생성 및 프로젝트에 적용
- [x] Util 관련 파일 추가
- [x] 리소스 관련 파일 추가
