### ISSUE TITLE
[Hotfix] Map View Bug Fix

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#21]
## Todo
- [x] `Error : unrecognized selector sent to instance ~` 오류 해결 
- [x] 서버통신 코드 개선
- [x] ~동 오류 : 문래동의 경우 문래동3가, 문래동6가 등이 존재하고 서버에서 데이터를 넘겨줄  때 띄어쓰기 유무로도 동의 이름이 바뀔 수 있는 에러 -> 문자열을 전달 받아, "동"을 기준으로 문자열을 자르고 해당 동 이름과 동일한 경우만 거점지 정보를 보여주는 것으로 해결
