### ISSUE TITLE
[UI] Splash UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#27]
## Todo
- [x] (런치스크린X) 스플래쉬 화면 구현
- [x] 애니메이션 구현 
- [x] 스플래쉬 -> 온보딩/메인 화면 분기처리
- [x] SceneDelegate에서 최초 화면 변경
