### ISSUE TITLE
[Refactor] Main 코드 개선

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#28]
## Todo
- [x] Main 초기화 버튼 구현
- [x] Main 중복되는 코드 정리 
- [x] 네트워크 코드 정리 
- [x] UI 수정
