### ISSUE TITLE
[Refactor] Main Bottom Sheet 코드 개선

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#29]
## Todo
- [x] 쏘카/그린카 리스트에서 객체로 구분
- [x] 데이터 전달 수정 
- [ ] 서버통신 코드 개선
