### ISSUE TITLE
[Feat] Custom Annotation View 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#40]
## Todo
- [ ] 쏘카/그린카 배열 구분
- [ ] 각 배열에 대한 네트워크 통신
- [ ] 쏘카/그린카 개수에 대한 annotation 분기처리
- [ ] clustering 적용
