### ISSUE TITLE
[Network] 디바이스 네트워크 연결상태 확인 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#43]
## Todo

- [x] 현재 디바이스가 네트워크에 연결된 상태인지 확인
- [x] 싱글톤 패턴 적용
- [x] Splash 화면에서 애니메이션 이후 분기처리
- [x] 각 화면에서 호출 (background -> foreground 진입 시)
