### ISSUE TITLE
[Fix] 디자인시스템 수정 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#63]
## Todo

- [x] TabBar 추가에 따른 네비게이션 UI 수정 > 디자인시스템 수정 
- [x] 네비게이션 타입 enum으로 관리 (push/popup)
- [x] 관련 코드 수정
