### ISSUE TITLE
[Feat] 주차장 상세 UI 구현

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#64]
## Todo

- [x] 주차장 상세 UI 구현 (MVVM) 
- [x] MVVM 구조 제대로 짜기 .. 
- [x] 데이터 전달 
- [x] 테이블뷰 UI -> UICollectionFlowLayout + UICollectionViewDataSource로 UI 구현 (이후에 Compositional+Diffable로 리펙토링)

**Comment by pcsoyeon** [comment]
### 작업한 것 
1020(목) - MVVM 으로 코드 개선 (현재 main 브랜치)

### 작업할 것 
- [x] 브랜치 새로 생성 후 전환해서 
- [x] Compositional Layout 적용(커스텀 셀 사용) 
- [x] Diffable Data Source 적용
