### ISSUE TITLE
[Network] 예약현황 API 연결 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#7]
## Todo
- [x] Network Base 파일 추가
- [x] 나눔카 예약현황 GET API 연결 (콘솔창에 데이터 찍기)
- [x] xml 데이터 파싱
- [x] Response 데이터 확인 후 UI 업데이트
