### ISSUE TITLE
[Refactor] 검색/상세 RxSwift, RxCocoa로 코드개선 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/NiCarNaeCar#72]
## Todo

- [x] 검색/상세화면 ViewModel 폴더 추가 및 폴더링 변경
- [x] RxSwift, RxCocoa로 실시간 검색 구현 
- [x] 데이터 전달 (지도화면으로)
